### ISSUE TITLE
Wishlist games with 0 reviews show NaN% positive

### ISSUE THREAD

**Issue by lachlancooper** [jshackles/Enhanced_Steam#1436]
As described. This is also visually distracting because the red thumbs down summary icon is displayed. Here's a couple of examples:

![capture](https://user-images.githubusercontent.com/660954/30248743-41fadd0e-9671-11e7-9e79-6441bcc9ceb1.png)

It might be best to omit the score and icon entirely for games with 0 reviews.

**Comment by JoiNNN** [comment]
Already fixed in #1426 👍

**Comment by ACeregini** [comment]
I'm still getting this. I was about to create a new issue but I think updating this is more appropriate. 
Games with 0 reviews are marked by the red thumb down of negativity, and the following label: "Nan% of the 0 user reviews for this game are positive".
This happens - obviously - for wishlisted games that are yet to be released. Here's an example:
![2017-10-23-10-35-steamcommunity com](https://user-images.githubusercontent.com/33021440/31879664-62dca7c6-b7de-11e7-81c5-c360cb97d8d9.png)

**Comment by lachlancooper** [comment]
Fixed as of version 9.6.
