### ISSUE TITLE
Broken work through HTTPS

### ISSUE THREAD

**Issue by thomas-ashcraft** [jshackles/Enhanced_Steam#857]
1) Yes, i saw https://github.com/jshackles/Enhanced_Steam/issues/574 and in my opinion its just stupid. Whoever will think that ES will intercepting their porno views over SSL can check opened sources of extension.

2) ES actually works on steam pages received through https, just some features is broken. Like on badge page.

This is how badges looks like over http
![bug badges https 1](https://cloud.githubusercontent.com/assets/6583664/10719773/f046d5fa-7b9f-11e5-9500-c1e73435efd6.png)

And this how badges looks like over https
![bug badges https 2](https://cloud.githubusercontent.com/assets/6583664/10719782/19088696-7ba0-11e5-8a5a-2124e7abf4ef.png)

Cloud icon at market page (which appear if have 10+ positions to sale) also dissapears if did not cached by browser from previously viewed through http.

that icon
http://store.akamai.steamstatic.com/public/images/v6/ico/ico_cloud.png

So main question is: does that illogical opinion about "intentional" still official and why then ES still trying to work over HTTPS?

**Comment by jshackles** [comment]
Enhanced Steam's API servers now work correctly over SSL -  #574 is very old at this point.

The issue you're experiencing on the badges page was fixed in 3faa47d and will be rolled out in the next release.

There are a few other pages where Enhanced Steam doesn't work as intended when pages are loaded via SSL - but in every instance it's because Steam's own servers won't allow the SSL connection, such as the icon you mentioned.

**Comment by thomas-ashcraft** [comment]
Partially fixed.
"Avg cost of completion" still does not work over HTTPS:
"div.badge_info_unlocked" does not even appear in result html code.

"#es_progress" status becomes red and his [title="Error loading Enhanced Steam data"]

Chrome console indicates:
XHR failed loading: GET "https://store.steampowered.com/app/220/".
add_badge_completion_cost	@	enhancedsteam.js:7265

Actually i cant open that link over HTTPS even manually

![bug badges https 3](https://cloud.githubusercontent.com/assets/6583664/10811991/b550f90a-7e22-11e5-8383-7ef4d7c21391.png)

**Comment by JoiNNN** [comment]
This was fixed since then. Can be closed.
